/*** Consultas ***/
Use CINEMARK2
Go
--1. La capacidad total de cada cine, así como el número de salas que tienen cada tipo desoporte.
Select A.CODIGO_CINE,Cine.NOMBRE,A.[CAPACIDAD TOTAL],A.TIPO_SOPORTE_DISPONIBLE, Cine.DIRECCION,CINE.TELEFONO
From (
	Select CODIGO_CINE,SUM(CAPACIDAD) as 'CAPACIDAD TOTAL',TIPO_SOPORTE_DISPONIBLE
	From SALA
	Group by CODIGO_CINE, TIPO_SOPORTE_DISPONIBLE
)A
Inner join CINE
On A.CODIGO_CINE=CINE.CODIGO_CINE
Order by A.CODIGO_CINE ASC
GO--------------NO TOCAR
--2. El mes que hubo más bajas de personal, por cine.
/*Select DATENAME(month,GETDATE());/*Obtener el nombre del mes*/
Select month(Fecha) From INactivo /*Obtener el mes donde se inactivaron mas trabajadores*/
Go*/
Select A.Meses, Count(1) as 'Cantidad de bajas',CODIGO_CINE
From (
	Select DATENAME(MONTH,INACTIVO.FECHA) AS 'Meses',INACTIVO.CODIGO_EMPLEADO FROM INACTIVO
)A
	INNER JOIN ACTIVO
		ON ACTIVO.CODIGO_EMPLEADO=A.CODIGO_EMPLEADO
Group by A.Meses,ACTIVO.CODIGO_CINE
ORDER BY [Cantidad de bajas] DESC
Go -----NO TOCAR
--3. El detalle del actor que ha aparecido en más peliculas regulares.
Select NOMBRE_ARTISTICO,COUNT(1) as 'Cantidad apariciones'
From REPARTO
Group by NOMBRE_ARTISTICO
ORDER BY [Cantidad apariciones] DESC
Go 
--4. El número de películas calificadas por los asistentes por calificación general (Obra Maestra, Muy Buena, Buena, Regular, Mala)
Select PELICULA.TITULO, CALIFICACION, COUNT(1) AS 'CANTIDAD CALIFICACION'
FROM OPINIONES
	INNER JOIN PELICULA
	ON OPINIONES.CODIGO_PELICULA=PELICULA.CODIGO_PELICULA
GROUP BY CALIFICACION, PELICULA.TITULO
GO   ------NO TOCAR
--5. Los detalles del cine con más bajas de personal.
SELECT TOP 1 CINE.NOMBRE,A.CODIGO_CINE,CINE.DIRECCION,CINE.TELEFONO,A.[CANTIDAD EN BAJA]
FROM(
SELECT ACTIVO.CODIGO_CINE,COUNT(1) AS 'CANTIDAD EN BAJA'
FROM INACTIVO
	INNER JOIN ACTIVO
		ON INACTIVO.CODIGO_EMPLEADO=ACTIVO.CODIGO_EMPLEADO
	GROUP BY ACTIVO.CODIGO_CINE
)A
INNER JOIN CINE
ON CINE.CODIGO_CINE=A.CODIGO_CINE
ORDER BY A.[CANTIDAD EN BAJA] DESC
GO------NO TOCAS
--6. La cartelera de la semana corriente de cada cine
SELECT EVENTO.CODIGO_CINE,CINE.NOMBRE, CARTELERA.CODIGO_PELICULA, PELICULA.TITULO, DATENAME(MONTH,EVENTO.FECHA) AS 'Mes',DATENAME (YEAR, EVENTO.FECHA) as 'Año'
FROM CARTELERA
	INNER JOIN EVENTO
		ON CARTELERA.CODIGO_PELICULA=EVENTO.CODIGO_PELICULA
	INNER JOIN PELICULA
		ON CARTELERA.CODIGO_PELICULA=PELICULA.CODIGO_PELICULA
	INNER JOIN CINE
		ON CINE.CODIGO_CINE=EVENTO.CODIGO_CINE
ORDER BY [Mes] desc
------------------BUSCAR COMO PONER MAXIMO-----------------------------------------------------

--7. El detalle de las películas regulares que se han exhibido en la sala más pequeña de cada cine.
SELECT EVENTO.CODIGO_PELICULA,SALA.NUMERO_SALA,SALA.CODIGO_CINE,SALA.CAPACIDAD
FROM(
	SELECT SALA.CODIGO_CINE, MIN(CAPACIDAD) AS 'CAPACIDAD' FROM SALA
	GROUP BY SALA.CODIGO_CINE
)A
	INNER JOIN SALA
		ON SALA.CAPACIDAD=A.CAPACIDAD AND SALA.CODIGO_CINE=A.CODIGO_CINE
	INNER JOIN EVENTO
		ON EVENTO.CODIGO_CINE=A.CODIGO_CINE AND EVENTO.NUMERO_SALA=SALA.NUMERO_SALA
	INNER JOIN PELICULA
		ON EVENTO.CODIGO_PELICULA=PELICULA.CODIGO_PELICULA
	INNER JOIN REGULARES
		ON EVENTO.CODIGO_PELICULA=REGULARES.CODIGO_PELICULA
GO 

--SELECT REGULARES.CODIGO_PELICULA,PELICULA.TITULO,SALA.TIPO_SOPORTE_DISPONIBLE,EVENTO.CODIGO_CINE,EVENTO.NUMERO_SALA,SALA.CAPACIDAD FROM REGULARES INNER JOIN PELICULA 
--ON REGULARES.CODIGO_PELICULA=PELICULA.CODIGO_PELICULA
--INNER JOIN EVENTO
--ON REGULARES.CODIGO_PELICULA=EVENTO.CODIGO_PELICULA
--INNER JOIN SALA
--ON EVENTO.NUMERO_SALA=SALA.NUMERO_SALA AND EVENTO.CODIGO_CINE=SALA.CODIGO_CINE

--8. El detalle del cine con mayores ventas en dulcería que en boletos.

--9. El listado de actores que aparecen en la película mejor evaluada.

--10. El detalle de los cines donde se exhibieron las 3 películas peor evaluadas.

--11. Los datos de las 10 películas de las que más boletos se han emitido.

--12. La duración promedio de los contenidos exhibidos por cine.
SELECT CINE.CODIGO_CINE,CINE.NOMBRE,CINE.DIRECCION,CINE.TELEFONO,A.[DURACION PROMEDIO]
FROM
(
	SELECT EVENTO.CODIGO_CINE, AVG(PELICULA.DURACION) AS 'DURACION PROMEDIO'
	FROM EVENTO
		INNER JOIN PELICULA
			ON PELICULA.CODIGO_PELICULA=EVENTO.CODIGO_PELICULA
	GROUP BY EVENTO.CODIGO_CINE
)A
INNER JOIN CINE
	ON A.CODIGO_CINE=CINE.CODIGO_CINE
GO---------------NO TOCAS

--13. El detalle del cliente que más visitas a Cinemark ha realizado, indicando el número de veces que ha visitado cada sede.

SELECT NIT,NOMBRE_CLIENTE,COUNT(1) AS 'CANTIDAD VISITAS'
FROM FACTURABOLETOS
FULL OUTER JOIN FACTURA_DULCERIA
	ON FACTURABOLETOS.NIT=FACTURA_DULCERIA.NIT
--GROUP BY NIT, NOMBRE_CLIENTE
ORDER BY [CANTIDAD VISITAS] DESC
GO
SELECT * FROM FACTURABOLETOS
------------------------------------PENDIENTE-------------------------

--14. Los dos productos más populares en dulcería por cine.
SELECT TOP 2 PRODUCTOS.DESCRIPCION,DULCES.TAMAÑO,DULCES.PRECIO,A.Cantidad
FROM(
	SELECT  DETALLEDULCERIA.CODIGO_PRODUCTO, COUNT(1) AS 'Cantidad'
	FROM FACTURA_DULCERIA
		INNER JOIN DETALLEDULCERIA
			ON FACTURA_DULCERIA.NUMERO_FACTURA=DETALLEDULCERIA.NUMERO_FACTURA
	GROUP BY DETALLEDULCERIA.CODIGO_PRODUCTO
)A
INNER JOIN DULCES
	ON A.CODIGO_PRODUCTO=DULCES.CODIGO_PRODUCTO
INNER JOIN PRODUCTOS
	ON A.CODIGO_PRODUCTO=PRODUCTOS.CODIGO_DULCE
ORDER BY A.Cantidad DESC
GO ---------------------NO TOCAZ

--15. El promedio de ventas totales por cine

--16. El listado contenidos que se han dejado de exhibir desde el primero de marzo en todos los cines.

--17. El nombre de los empleados que han laborado en el cine con mayores ventas.

--18. El número de exhibiciones culturales y deportivas que se han proyectado por cine.
SELECT EVENTO.CODIGO_CINE, COUNT(1) AS 'CANTIDAD DE VECES PROYECTADAS'
FROM EVENTO
	INNER JOIN ESPECIALES
		ON EVENTO.CODIGO_PELICULA=ESPECIALES.CODIGO_PELICULA
GROUP BY EVENTO.CODIGO_CINE
GO
--19. El mes que menos boletos se vendieron, pero más productos de dulcería se vendieron.
--20. El detalle de los clientes que nunca han consumido algo de las dulcerías en alguna de sus visitas

